[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redireciona 404 para a página inicial
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

